#!/bin/sh

killall -q sxhkd; sxhkd &
setxkbmap cz &

bspc monitor -d 1 2 3 4

bspc config pointer_motion_interval 5
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config pointer_follows_monitor true

bspc config border_width  4
bspc config window_gap    15

bspc config split_ratio          0.52
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#61afef"
bspc config normal_border_color  "#1e222a"

# Ordering windows
bspc rule -a kitty           desktop='^1' follow=on
bspc rule -a firefox         desktop='^1'
#bspc rule -a Brave-browser   desktop='^2'
bspc rule -a vlc             desktop='^2'
bspc rule -a discord         desktop='^2' state=floating
bspc rule -a Spotify         desktop='^2'
bspc rule -a Steam           desktop='^3'
bspc rule -a 'Steam:*:Friends List' desktop='^3' state=floating
#bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Lutris          desktop='^3'
#bspc rule -a Gimp-2.10       desktop='^7'
bspc rule -a Code            desktop='^4'
bspc rule -a qBittorrent     desktop='^1'
#bspc rule -a Evince          desktop='^8'

bspc rule -a feh                state=floating
bspc rule -a Org.gnome.Nautilus state=floating

# games
bspc rule -a robloxplayerlauncher.exe desktop='^2' state=floating
bspc rule -a robloxplayerbeta.exe     desktop='^5'
bspc rule -a hl2_linux                desktop='^5'

steamlib=/media/gamedisk/SteamLibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')

for game in $mygames; do
  bspc rule -a steam_app_$game desktop=^4
done




###################
# AUTOSTART APPS #
##################

killall -q dunst; dunst & #Kills dunst if it's running and launches it again
polybar & # Polybar - Status bar
nitrogen --restore & # Restores and changes my last wallpaper
picom
